import { getAuthSession } from "@/app/api/auth/[...nextauth]/auth";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Recruiter Dashboard",
    description: "Generated by create next app",
};


export default async function RootLayout({
    children,
}: {
    children: ReactNode,
}) {

    const session = await getAuthSession();

    if(session?.user.role != "RECRUITER") redirect("/");

    return (
        <>
            {children}
        </>
    );
}
