import { getAuthSession } from "@/app/api/auth/[...nextauth]/auth";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

export const metadata = {
  title: "Candidate Dash",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: ReactNode;
}) {

  const session = await getAuthSession();
  console.log("Candidate Dashboard");

  // You can return early if you need a redirection here
  if (session && session?.user.role !== "CANDIDATE") redirect("/")

  return (
    <>
      {children}
    </>
  );
}
